//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRMBasics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMCompany
    {
        public int c_id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> registration { get; set; }
        public string companyType { get; set; }
        public Nullable<int> noEmp { get; set; }
        public string serviceOne { get; set; }
        public string serviceTwo { get; set; }
        public string serviceThree { get; set; }
        public string address { get; set; }
        public string country { get; set; }
        public string province { get; set; }
        public string city { get; set; }
    }
}
